# Generated by Django 4.1 on 2022-08-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mypolice', '0002_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='missingperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('zip', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
    ]
