# Generated by Django 4.1 on 2022-08-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mypolice', '0003_missingperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
